### get datastories

http://localhost/get_data_stories



### get_datastory?ds=<uuid>

http://localhost/get_item?ds=66081fa0-b4c2-4c16-a708-c02510ccebb3

### update datastory

POST http://localhost/update_datastory 
Content-type: application/json

{
    "datastory_id": "c568ba14-a92f-47e2-b98f-9923d93a80b1",
    "testding" : "abracadabra",
    "datastory": {
        "title": "klootzak",
        "owner": "Rob"
    }


}


### get datastories

http://localhost/get_data_stories



### OPTIONS test

OPTIONS  http://localhost/browse

###

### UPLOAD endpoint

POST http://localhost/upload



https://stackoverflow.com/questions/10434599/get-the-data-received-in-a-flask-request